// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dsplitt
NumericVector dsplitt(NumericVector x, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd, bool logarithm);
RcppExport SEXP dng_dsplitt(SEXP xSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP, SEXP logarithmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    Rcpp::traits::input_parameter< bool >::type logarithm(logarithmSEXP);
    rcpp_result_gen = Rcpp::wrap(dsplitt(x, mu, df, phi, lmd, logarithm));
    return rcpp_result_gen;
END_RCPP
}
// splitt_kurtosis
NumericVector splitt_kurtosis(NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_kurtosis(SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_kurtosis(df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// splitt_mean
NumericVector splitt_mean(NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_mean(SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_mean(mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// psplitt
NumericVector psplitt(NumericVector q, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_psplitt(SEXP qSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(psplitt(q, mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// qsplitt
NumericVector qsplitt(NumericVector p, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_qsplitt(SEXP pSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(qsplitt(p, mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// rsplitt
NumericVector rsplitt(int n, NumericVector mu, NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_rsplitt(SEXP nSEXP, SEXP muSEXP, SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(rsplitt(n, mu, df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// splitt_skewness
NumericVector splitt_skewness(NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_skewness(SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_skewness(df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}
// splitt_var
NumericVector splitt_var(NumericVector df, NumericVector phi, NumericVector lmd);
RcppExport SEXP dng_splitt_var(SEXP dfSEXP, SEXP phiSEXP, SEXP lmdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lmd(lmdSEXP);
    rcpp_result_gen = Rcpp::wrap(splitt_var(df, phi, lmd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"dng_dsplitt", (DL_FUNC) &dng_dsplitt, 6},
    {"dng_splitt_kurtosis", (DL_FUNC) &dng_splitt_kurtosis, 3},
    {"dng_splitt_mean", (DL_FUNC) &dng_splitt_mean, 4},
    {"dng_psplitt", (DL_FUNC) &dng_psplitt, 5},
    {"dng_qsplitt", (DL_FUNC) &dng_qsplitt, 5},
    {"dng_rsplitt", (DL_FUNC) &dng_rsplitt, 5},
    {"dng_splitt_skewness", (DL_FUNC) &dng_splitt_skewness, 3},
    {"dng_splitt_var", (DL_FUNC) &dng_splitt_var, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dng(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
