# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsplitt <- function(x, mu, df, phi, lmd, logarithm) {
    .Call(dng_dsplitt, x, mu, df, phi, lmd, logarithm)
}

splitt_kurtosis <- function(df, phi, lmd) {
    .Call(dng_splitt_kurtosis, df, phi, lmd)
}

splitt_mean <- function(mu, df, phi, lmd) {
    .Call(dng_splitt_mean, mu, df, phi, lmd)
}

psplitt <- function(q, mu, df, phi, lmd) {
    .Call(dng_psplitt, q, mu, df, phi, lmd)
}

qsplitt <- function(p, mu, df, phi, lmd) {
    .Call(dng_qsplitt, p, mu, df, phi, lmd)
}

rsplitt <- function(n, mu, df, phi, lmd) {
    .Call(dng_rsplitt, n, mu, df, phi, lmd)
}

splitt_skewness <- function(df, phi, lmd) {
    .Call(dng_splitt_skewness, df, phi, lmd)
}

splitt_var <- function(df, phi, lmd) {
    .Call(dng_splitt_var, df, phi, lmd)
}

